force-app/main/default/objects/Translation__c/Translation__c.object-meta.xml
<CustomObject>
    <description>Represents a specific translation of an existing record. This object should have a lookup relationship to the object it is a translation of.</description>
    <label>Translation</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Translation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Translation__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>The name of the field on Object Name to be translated.</description>
    <label>Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>The name of the object the translation is associated with</description>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>The record id for which the translation is associated</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Slug__c.field-meta.xml
<CustomField>
    <fullName>Slug__c</fullName>
    <description>The title of the submitted translation</description>
    <label>Slug</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Source_Content__c.field-meta.xml
<CustomField>
    <fullName>Source_Content__c</fullName>
    <description>The original content to be translated</description>
    <label>Source Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Source_Language__c.field-meta.xml
<CustomField>
    <fullName>Source_Language__c</fullName>
    <description>The ISO code of the language in the original record</description>
    <label>Source Language</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Source_Language_Code__c.field-meta.xml
<CustomField>
    <fullName>Source_Language_Code__c</fullName>
    <description>The ISO code of the original language</description>
    <label>Source Language Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the translation</description>
    <label>Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Target_Language__c.field-meta.xml
<CustomField>
    <fullName>Target_Language__c</fullName>
    <description>The ISO code of the language the original record is to be translated to</description>
    <label>Target Language</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Target_Language_Code__c.field-meta.xml
<CustomField>
    <fullName>Target_Language_Code__c</fullName>
    <description>The ISO code of the target language</description>
    <label>Target Language Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TranslationControllerTest.cls
@isTest
private class TranslationControllerTest {
    
    @testSetup 
    static void setup() {
        Case sampleCase = new Case(
            Subject = 'Test case subject',
            Description = 'Test case description'

        );

        insert sampleCase;

        List<Translation__c> translations = new List<Translation__c>();

        translations.add(new Translation__c(
            Record_Id__c = sampleCase.Id,
            Status__c = 'available',
            Slug__c = 'Translation :: English to French',
            Source_Language__c = 'English',
            Source_Language_Code__c = 'en',
            Target_Language__c = 'French',
            Target_Language_Code__c = 'fr',
            Object_Name__c = 'Case',
            Field_Name__c = 'Description',
            Source_Content__c = 'Test case description'
        ));

        translations.add(new Translation__c(
            Record_Id__c = sampleCase.Id,
            Status__c = 'available',
            Slug__c = 'Translation :: English to Italian',
            Source_Language__c = 'English',
            Source_Language_Code__c = 'en',
            Target_Language__c = 'Italian',
            Target_Language_Code__c = 'it',
            Object_Name__c = 'Case',
            Field_Name__c = 'Description',
            Source_Content__c = 'Test case description'
        ));

        translations.add(new Translation__c(
            Record_Id__c = sampleCase.Id,
            Status__c = 'available',
            Slug__c = 'Translation :: English to German',
            Source_Language__c = 'English',
            Source_Language_Code__c = 'en',
            Target_Language__c = 'German',
            Target_Language_Code__c = 'de',
            Object_Name__c = 'Case',
            Field_Name__c = 'Description',
            Source_Content__c = 'Test case description'
        ));

        insert translations;
    }

    static List<Case> getCases() {
        return [
            SELECT 
                Id 
            FROM 
                Case
        ];
    }

    static List<Translation__c> getTranslations() {
        return [
            SELECT 
                Id 
            FROM 
                Translation__c
        ];
    }

    static List<Translation__c> getTranslationsByLanguage(String sourceLanguageCode, String targetLanguageCode) {
        return [
            SELECT 
                Id 
            FROM 
                Translation__c
            WHERE 
                Source_Language_Code__c = :sourceLanguageCode
                AND Target_Language_Code__c = :targetLanguageCode
        ];
    }

    static List<Translation__c> getTranslationById(String translationId) {
        return [
            SELECT 
                Id 
            FROM 
                Translation__c
            WHERE 
                Id = :translationId
        ];
    }

    @isTest 
    static void testRetrieveTranslations_All() {
        List<Case> cases = getCases();

        Id caseId = cases.get(0).Id;

        Test.startTest();
        TranslationController.PagedResult result = TranslationController.retrieveTranslations(caseId, '{"status":"","sourceLanguage":"","targetLanguage":""}', 5, 1);
        Test.stopTest();

        List<Translation__c> translations = getTranslations();

        System.assertEquals(translations.size(), result.total);
    }

    @isTest 
    static void testRetrieveTranslations_Available() {
        List<Case> cases = getCases();

        Id caseId = cases.get(0).Id;

        Test.startTest();
        TranslationController.PagedResult result = TranslationController.retrieveTranslations(caseId, '{"status":"available","sourceLanguage":"","targetLanguage":""}', 5, 1);
        Test.stopTest();

        List<Translation__c> translations = getTranslations();

        System.assertEquals(translations.size(), result.total);
    }

    @isTest 
    static void testRetrieveTranslations_Pending() {
        List<Case> cases = getCases();

        Id caseId = cases.get(0).Id;

        Test.startTest();
        TranslationController.PagedResult result = TranslationController.retrieveTranslations(caseId, '{"status":"pending","sourceLanguage":"","targetLanguage":""}', 5, 1);
        Test.stopTest();

        List<Translation__c> translations = getTranslations();

        System.assertNotEquals(translations.size(), result.total);
        System.assertEquals(0, result.total);
    }

    @isTest 
    static void testRetrieveTranslations_EnglishToFrench() {
        List<Case> cases = getCases();

        Id caseId = cases.get(0).Id;

        Test.startTest();
        TranslationController.PagedResult result = TranslationController.retrieveTranslations(caseId, '{"status":"","sourceLanguage":"en","targetLanguage":"fr"}', 5, 1);
        Test.stopTest();

        List<Translation__c> translations = getTranslationsByLanguage('en', 'fr');

        System.assertEquals(translations.size(), result.total);
    }

    @isTest 
    static void testRetrieveTranslations_EnglishToItalian() {
        List<Case> cases = getCases();

        Id caseId = cases.get(0).Id;

        Test.startTest();
        TranslationController.PagedResult result = TranslationController.retrieveTranslations(caseId, '{"status":"","sourceLanguage":"en","targetLanguage":"it"}', 5, 1);
        Test.stopTest();

        List<Translation__c> translations = getTranslationsByLanguage('en', 'it');

        System.assertEquals(translations.size(), result.total);
    }

    @isTest 
    static void testRetrieveTranslations_EnglishToGerman() {
        List<Case> cases = getCases();

        Id caseId = cases.get(0).Id;

        Test.startTest();
        TranslationController.PagedResult result = TranslationController.retrieveTranslations(caseId, '{"status":"","sourceLanguage":"en","targetLanguage":"de"}', 5, 1);
        Test.stopTest();

        List<Translation__c> translations = getTranslationsByLanguage('en', 'de');

        System.assertEquals(translations.size(), result.total);
    }

    @isTest 
    static void testRetrieveTranslations_EnglishToSpanish() {
        List<Case> cases = getCases();

        Id caseId = cases.get(0).Id;

        Test.startTest();
        TranslationController.PagedResult result = TranslationController.retrieveTranslations(caseId, '{"status":"","sourceLanguage":"en","targetLanguage":"es"}', 5, 1);
        Test.stopTest();

        List<Translation__c> translations = getTranslationsByLanguage('en', 'es');

        System.assertEquals(translations.size(), result.total);
        System.assertEquals(0, result.total);
    }

    @isTest 
    static void testRetrieveTranslation() {
        List<Translation__c> translations = getTranslations();

        Id translationId = translations.get(0).Id;

        Test.startTest();
        String translation = TranslationController.retrieveTranslation(translationId);
        Test.stopTest();

        List<Translation__c> trans = getTranslationById(translationId);

        System.assert(!trans.isEmpty());

        Translation__c tran = trans.get(0);

        System.assertEquals(translationId, tran.Id);
    }

    
}