force-app/main/default/objects/Translation__c/Translation__c.object-meta.xml
<CustomObject>
    <description>Represents a specific translation of an existing record. This object should have a lookup relationship to the object it is a translation of.</description>
    <label>Translation</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Translation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Translation__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <description>The job id (order id) of the submitted translation</description>
    <label>Job Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <description>The id of the order associated with the translation job</description>
    <label>Order Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TranslationJobUpdateQueueable.cls
public class TranslationJobUpdateQueueable implements Queueable, Database.AllowsCallouts {
    private String orderId;
    private TranslationService service;

    public TranslationJobUpdateQueueable(String orderId) {
        this.orderId = orderId;
        this.service = new GengoService();
    }

    public void execute(QueueableContext context) {
        Boolean successfullyUpdated = false;

        if (String.isNotBlank(this.orderId)) {
            try {
                String result = this.service.getOrder(this.orderId);
                
                GengoResponse.TranslationOrderResponse tor = (GengoResponse.TranslationOrderResponse)JSON.deserialize(result, GengoResponse.TranslationOrderResponse.class);
            
                if (tor.opstat == GengoConstants.OK_STATUS) {
                    GengoResponse.RetrieveResponse rr = tor.response;

                    if (rr.order != null) {
                        List<Translation__c> translations = retrieveTranslations(this.orderId);
                        List<Integer> jobIds = rr.order.jobs_available;

                        for (Translation__c translation: translations) {
                            for (Integer jobId: jobIds) {
                                translation.Job_Id__c = String.valueOf(jobId);
                            }
                        }

                        update translations;
                    }
                }
            } catch (Exception e) {
                System.debug('ERROR: ' + e.getMessage());
            }
        }

        if (!successfullyUpdated) {
            System.enqueueJob(this);
        }
    }

    private List<Translation__c> retrieveTranslations(String orderId) {
        return [
            SELECT 
                Id,
                Job_Id__c
            FROM 
                Translation__c 
            WHERE 
                Order_Id__c = :orderId
        ];
    }
}