force-app/main/default/objects/Translation__c/Translation__c.object-meta.xml
<CustomObject>
    <description>Represents a specific translation of an existing record. This object should have a lookup relationship to the object it is a translation of.</description>
    <label>Translation</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Translation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Translation__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <description>The id of the order associated with the translation job</description>
    <label>Order Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the translation</description>
    <label>Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Translated_Content__c.field-meta.xml
<CustomField>
    <fullName>Translated_Content__c</fullName>
    <description>Contains the translated content of the original source record field</description>
    <label>Translated Content</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/GengoCallbackHandler.cls
@RestResource(urlMapping='/order')
global class GengoCallbackHandler {
    
    @HttpPost
    global static void doOrderPost() {
        String job = RestContext.request.params.get('job');

        if (job != null) {
            Map<String, Object> jobMap = (Map<String, Object>)JSON.deserializeUntyped(job);

            String bodyTgt = (String)jobMap.get(GengoConstants.JOB_TARGET_CONTENT);

            if (jobMap.containsKey(GengoConstants.JOB_ORDER_ID)) {
                String orderId = (String)jobMap.get(GengoConstants.JOB_ORDER_ID);
                
                String soql = 'SELECT Id, Status__c FROM Translation__c WHERE Order_Id__c = :orderId';
                
                List<Translation__c> translations = Database.query(soql);

                if (jobMap.containsKey(GengoConstants.JOB_STATUS)) {
                    String status = (String)jobMap.get(GengoConstants.JOB_STATUS);
                    
                    for (Translation__c translation: translations) {
                        translation.Status__c = status;
                        translation.Translated_Content__c = bodyTgt;
                    }

                    update translations;
                }
            }
        }
    }
}