force-app/main/default/objects/Translation__c/Translation__c.object-meta.xml
<CustomObject>
    <description>Represents a specific translation of an existing record. This object should have a lookup relationship to the object it is a translation of.</description>
    <label>Translation</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Translation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Translation__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <description>The job id (order id) of the submitted translation</description>
    <label>Job Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <description>The id of the order associated with the translation job</description>
    <label>Order Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Translation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of the translation</description>
    <label>Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TranslationProcessBatch.cls
global with sharing class TranslationProcessBatch implements Database.Batchable<SObject>, Database.AllowsCallouts, Database.Stateful {
    private final String query;
    private final Set<String> STATUSES = new Set<String>{
        'queued',
        'available',
        'pending',
        'revising',
        'reviewable'
    };

    private OrderService service;
    
    public TranslationProcessBatch() {
        this.service = new OrderService();
        this.query = 'SELECT Id, Status__c, Order_Id__c, Job_Id__c FROM Translation__c WHERE Status__c IN (:STATUSES)';
    }

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bd, List<SObject> records) {
        List<Translation__c> translations = (List<Translation__c>)records;

        Map<String, Map<String, Translation__c>> translationsOrderToJobMap = new Map<String, Map<String, Translation__c>>();

        for (Translation__c translation: translations) {
            if (!translationsOrderToJobMap.containsKey(translation.Order_Id__c)) {
                translationsOrderToJobMap.put(translation.Order_Id__c, new Map<String, Translation__c>());
            } 

            Map<String, Translation__c> jobMap = translationsOrderToJobMap.get(translation.Order_Id__c);
            jobMap.put(translation.Job_Id__c, translation);
            translationsOrderToJobMap.put(translation.Job_Id__c, jobMap);
        }

        List<Translation__c> translationsToUpdate = new List<Translation__c>();

        for (String orderId: translationsOrderToJobMap.keySet()) {
            List<Translation__c> trans = this.service.updateJobs(orderId, translationsOrderToJobMap.get(orderId));

            if (!trans.isEmpty()) {
                translationsToUpdate.addAll(trans);
            }
        }

        if (!translationsToUpdate.isEmpty()) {
            update translations;
        }
    }

    global void finish(Database.BatchableContext bc) {}
}